# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
District.destroy_all
Zipcode.destroy_all

one = District.create(name: "1st", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Virginia_US_Congressional_District_1_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_1_%28since_2013%29.tif.png")
two = District.create(name: "2nd", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Virginia_US_Congressional_District_2_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_2_%28since_2013%29.tif.png")
three = District.create(name: "3rd", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Virginia_US_Congressional_District_3_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_3_%28since_2013%29.tif.png")
four = District.create(name: "4th", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Virginia_US_Congressional_District_4_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_4_%28since_2013%29.tif.png")
five = District.create(name: "5th", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Virginia_US_Congressional_District_5_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_5_%28since_2013%29.tif.png")
six = District.create(name: "6th", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Virginia_US_Congressional_District_6_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_6_%28since_2013%29.tif.png")
seven = District.create(name: "7th", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Virginia_US_Congressional_District_7_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_7_%28since_2013%29.tif.png")
eight = District.create(name: "8th", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Virginia_US_Congressional_District_8_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_8_%28since_2013%29.tif.png")
nine = District.create(name: "9th", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Virginia_US_Congressional_District_9_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_9_%28since_2013%29.tif.png")
ten = District.create(name: "10th", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Virginia_US_Congressional_District_10_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_10_%28since_2013%29.tif.png")
eleven = District.create(name: "11th", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Virginia_US_Congressional_District_11_%28since_2013%29.tif/lossless-page1-800px-Virginia_US_Congressional_District_11_%28since_2013%29.tif.png")

perry = one.candidates.create(name: "Perry", party: "Perrycrat")

Zipcode.create(zip: 20105).distzips.create([{district: ten}])
Zipcode.create(zip: 20106).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 20109).distzips.create([{district: one}, {district: ten}])
Zipcode.create(zip: 20110).distzips.create([{district: one}, {district: ten}])
Zipcode.create(zip: 20111).distzips.create([{district: one}, {district: ten}])
Zipcode.create(zip: 20112).distzips.create([{district: one}, {district: ten}, {district: eleven}])
Zipcode.create(zip: 20115).distzips.create([{district: five}])
Zipcode.create(zip: 20117).distzips.create([{district: five}, {district: ten}])
Zipcode.create(zip: 20118).distzips.create([{district: ten}])
Zipcode.create(zip: 20119).distzips.create([{district: one}, {district: five}])
Zipcode.create(zip: 20120).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20121).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20124).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20129).distzips.create([{district: ten}])
Zipcode.create(zip: 20130).distzips.create([{district: five}, {district: ten}])
Zipcode.create(zip: 20132).distzips.create([{district: ten}])
Zipcode.create(zip: 20135).distzips.create([{district: ten}])
Zipcode.create(zip: 20136).distzips.create([{district: one}])
Zipcode.create(zip: 20137).distzips.create([{district: five}, {district: ten}])
Zipcode.create(zip: 20139).distzips.create([{district: five}])
Zipcode.create(zip: 20141).distzips.create([{district: ten}])
Zipcode.create(zip: 20143).distzips.create([{district: ten}])
Zipcode.create(zip: 20144).distzips.create([{district: five}])
Zipcode.create(zip: 20147).distzips.create([{district: ten}])
Zipcode.create(zip: 20148).distzips.create([{district: ten}])
Zipcode.create(zip: 20151).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20152).distzips.create([{district: ten}])
Zipcode.create(zip: 20155).distzips.create([{district: one}, {district: ten}])
Zipcode.create(zip: 20158).distzips.create([{district: ten}])
Zipcode.create(zip: 20164).distzips.create([{district: ten}])
Zipcode.create(zip: 20165).distzips.create([{district: ten}])
Zipcode.create(zip: 20166).distzips.create([{district: ten}])
Zipcode.create(zip: 20169).distzips.create([{district: ten}])
Zipcode.create(zip: 20170).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20171).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20175).distzips.create([{district: ten}])
Zipcode.create(zip: 20176).distzips.create([{district: ten}])
Zipcode.create(zip: 20180).distzips.create([{district: ten}])
Zipcode.create(zip: 20181).distzips.create([{district: one}, {district: five}])
Zipcode.create(zip: 20184).distzips.create([{district: five}, {district: ten}])
Zipcode.create(zip: 20186).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 20187).distzips.create([{district: five}])
Zipcode.create(zip: 20190).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20191).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20194).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 20197).distzips.create([{district: ten}])
Zipcode.create(zip: 20198).distzips.create([{district: five}])
Zipcode.create(zip: 22003).distzips.create([{district: eight}, {district: eleven}])
Zipcode.create(zip: 22015).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 22025).distzips.create([{district: one}])
Zipcode.create(zip: 22026).distzips.create([{district: one}, {district: eleven}])
Zipcode.create(zip: 22027).distzips.create([{district: eleven}])
Zipcode.create(zip: 22030).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 22031).distzips.create([{district: eleven}])
Zipcode.create(zip: 22032).distzips.create([{district: eleven}])
Zipcode.create(zip: 22033).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 22035).distzips.create([{district: eleven}])
Zipcode.create(zip: 22039).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 22041).distzips.create([{district: eight}, {district: eleven}])
Zipcode.create(zip: 22042).distzips.create([{district: eight}, {district: eleven}])
Zipcode.create(zip: 22043).distzips.create([{district: eight}, {district: eleven}])
Zipcode.create(zip: 22044).distzips.create([{district: eight}, {district: eleven}])
Zipcode.create(zip: 22046).distzips.create([{district: eight}])
Zipcode.create(zip: 22060).distzips.create([{district: eight}])
Zipcode.create(zip: 22066).distzips.create([{district: ten}])
Zipcode.create(zip: 22079).distzips.create([{district: eight}, {district: ten}, {district: eleven}])
Zipcode.create(zip: 22101).distzips.create([{district: eight}, {district: ten}])
Zipcode.create(zip: 22102).distzips.create([{district: eight}, {district: ten}, {district: eleven}])
Zipcode.create(zip: 22124).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 22125).distzips.create([{district: eleven}])
Zipcode.create(zip: 22134).distzips.create([{district: one}, {district: eleven}])
Zipcode.create(zip: 22150).distzips.create([{district: eight}, {district: eleven}])
Zipcode.create(zip: 22151).distzips.create([{district: eight}, {district: eleven}])
Zipcode.create(zip: 22152).distzips.create([{district: eleven}])
Zipcode.create(zip: 22153).distzips.create([{district: eight}, {district: ten}, {district: eleven}])
Zipcode.create(zip: 22172).distzips.create([{district: one}, {district: eleven}])
Zipcode.create(zip: 22180).distzips.create([{district: eleven}])
Zipcode.create(zip: 22181).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 22182).distzips.create([{district: ten}, {district: eleven}])
Zipcode.create(zip: 22185).distzips.create([{district: eleven}])
Zipcode.create(zip: 22191).distzips.create([{district: eleven}])
Zipcode.create(zip: 22192).distzips.create([{district: one}, {district: eleven}])
Zipcode.create(zip: 22193).distzips.create([{district: one}, {district: eleven}])
Zipcode.create(zip: 22201).distzips.create([{district: eight}])
Zipcode.create(zip: 22202).distzips.create([{district: eight}])
Zipcode.create(zip: 22203).distzips.create([{district: eight}])
Zipcode.create(zip: 22204).distzips.create([{district: eight}])
Zipcode.create(zip: 22205).distzips.create([{district: eight}])
Zipcode.create(zip: 22206).distzips.create([{district: eight}])
Zipcode.create(zip: 22207).distzips.create([{district: eight}])
Zipcode.create(zip: 22209).distzips.create([{district: eight}])
Zipcode.create(zip: 22211).distzips.create([{district: eight}])
Zipcode.create(zip: 22213).distzips.create([{district: eight}])
Zipcode.create(zip: 22214).distzips.create([{district: eight}])
Zipcode.create(zip: 22301).distzips.create([{district: eight}])
Zipcode.create(zip: 22302).distzips.create([{district: eight}])
Zipcode.create(zip: 22303).distzips.create([{district: eight}])
Zipcode.create(zip: 22304).distzips.create([{district: eight}])
Zipcode.create(zip: 22305).distzips.create([{district: eight}])
Zipcode.create(zip: 22306).distzips.create([{district: eight}])
Zipcode.create(zip: 22307).distzips.create([{district: eight}])
Zipcode.create(zip: 22308).distzips.create([{district: eight}])
Zipcode.create(zip: 22309).distzips.create([{district: eight}])
Zipcode.create(zip: 22310).distzips.create([{district: eight}])
Zipcode.create(zip: 22311).distzips.create([{district: eight}])
Zipcode.create(zip: 22312).distzips.create([{district: eight}])
Zipcode.create(zip: 22314).distzips.create([{district: eight}])
Zipcode.create(zip: 22315).distzips.create([{district: eight}])
Zipcode.create(zip: 22401).distzips.create([{district: one}])
Zipcode.create(zip: 22405).distzips.create([{district: one}])
Zipcode.create(zip: 22406).distzips.create([{district: one}])
Zipcode.create(zip: 22407).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 22408).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 22427).distzips.create([{district: one}])
Zipcode.create(zip: 22432).distzips.create([{district: one}])
Zipcode.create(zip: 22433).distzips.create([{district: seven}])
Zipcode.create(zip: 22435).distzips.create([{district: one}])
Zipcode.create(zip: 22436).distzips.create([{district: one}])
Zipcode.create(zip: 22437).distzips.create([{district: one}])
Zipcode.create(zip: 22438).distzips.create([{district: one}])
Zipcode.create(zip: 22443).distzips.create([{district: one}])
Zipcode.create(zip: 22448).distzips.create([{district: one}])
Zipcode.create(zip: 22454).distzips.create([{district: one}])
Zipcode.create(zip: 22460).distzips.create([{district: one}])
Zipcode.create(zip: 22469).distzips.create([{district: one}])
Zipcode.create(zip: 22473).distzips.create([{district: one}])
Zipcode.create(zip: 22476).distzips.create([{district: one}])
Zipcode.create(zip: 22480).distzips.create([{district: one}])
Zipcode.create(zip: 22482).distzips.create([{district: one}])
Zipcode.create(zip: 22485).distzips.create([{district: one}])
Zipcode.create(zip: 22488).distzips.create([{district: one}])
Zipcode.create(zip: 22503).distzips.create([{district: one}])
Zipcode.create(zip: 22504).distzips.create([{district: one}])
Zipcode.create(zip: 22508).distzips.create([{district: seven}])
Zipcode.create(zip: 22509).distzips.create([{district: one}])
Zipcode.create(zip: 22511).distzips.create([{district: one}])
Zipcode.create(zip: 22514).distzips.create([{district: one}])
Zipcode.create(zip: 22520).distzips.create([{district: one}])
Zipcode.create(zip: 22529).distzips.create([{district: one}])
Zipcode.create(zip: 22530).distzips.create([{district: one}])
Zipcode.create(zip: 22534).distzips.create([{district: seven}])
Zipcode.create(zip: 22535).distzips.create([{district: one}])
Zipcode.create(zip: 22538).distzips.create([{district: one}])
Zipcode.create(zip: 22539).distzips.create([{district: one}])
Zipcode.create(zip: 22542).distzips.create([{district: seven}])
Zipcode.create(zip: 22546).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 22548).distzips.create([{district: one}])
Zipcode.create(zip: 22551).distzips.create([{district: seven}])
Zipcode.create(zip: 22553).distzips.create([{district: seven}])
Zipcode.create(zip: 22554).distzips.create([{district: one}])
Zipcode.create(zip: 22556).distzips.create([{district: one}])
Zipcode.create(zip: 22560).distzips.create([{district: one}])
Zipcode.create(zip: 22567).distzips.create([{district: seven}])
Zipcode.create(zip: 22572).distzips.create([{district: one}])
Zipcode.create(zip: 22576).distzips.create([{district: one}])
Zipcode.create(zip: 22578).distzips.create([{district: one}])
Zipcode.create(zip: 22579).distzips.create([{district: one}])
Zipcode.create(zip: 22580).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 22601).distzips.create([{district: ten}])
Zipcode.create(zip: 22602).distzips.create([{district: ten}])
Zipcode.create(zip: 22603).distzips.create([{district: ten}])
Zipcode.create(zip: 22610).distzips.create([{district: six}])
Zipcode.create(zip: 22611).distzips.create([{district: ten}])
Zipcode.create(zip: 22620).distzips.create([{district: ten}])
Zipcode.create(zip: 22623).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 22624).distzips.create([{district: ten}])
Zipcode.create(zip: 22625).distzips.create([{district: ten}])
Zipcode.create(zip: 22627).distzips.create([{district: five}])
Zipcode.create(zip: 22630).distzips.create([{district: five}, {district: six}, {district: ten}])
Zipcode.create(zip: 22637).distzips.create([{district: ten}])
Zipcode.create(zip: 22639).distzips.create([{district: five}])
Zipcode.create(zip: 22640).distzips.create([{district: five}])
Zipcode.create(zip: 22641).distzips.create([{district: six}])
Zipcode.create(zip: 22642).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 22643).distzips.create([{district: five}])
Zipcode.create(zip: 22644).distzips.create([{district: six}])
Zipcode.create(zip: 22645).distzips.create([{district: six}, {district: ten}])
Zipcode.create(zip: 22646).distzips.create([{district: ten}])
Zipcode.create(zip: 22650).distzips.create([{district: six}])
Zipcode.create(zip: 22652).distzips.create([{district: six}])
Zipcode.create(zip: 22654).distzips.create([{district: six}, {district: ten}])
Zipcode.create(zip: 22655).distzips.create([{district: six}, {district: ten}])
Zipcode.create(zip: 22656).distzips.create([{district: ten}])
Zipcode.create(zip: 22657).distzips.create([{district: six}])
Zipcode.create(zip: 22660).distzips.create([{district: six}])
Zipcode.create(zip: 22663).distzips.create([{district: ten}])
Zipcode.create(zip: 22664).distzips.create([{district: six}])
Zipcode.create(zip: 22701).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22709).distzips.create([{district: five}])
Zipcode.create(zip: 22711).distzips.create([{district: five}])
Zipcode.create(zip: 22712).distzips.create([{district: one}, {district: five}])
Zipcode.create(zip: 22713).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22714).distzips.create([{district: seven}])
Zipcode.create(zip: 22715).distzips.create([{district: five}])
Zipcode.create(zip: 22716).distzips.create([{district: five}])
Zipcode.create(zip: 22718).distzips.create([{district: seven}])
Zipcode.create(zip: 22719).distzips.create([{district: five}])
Zipcode.create(zip: 22720).distzips.create([{district: one}])
Zipcode.create(zip: 22722).distzips.create([{district: five}])
Zipcode.create(zip: 22723).distzips.create([{district: five}])
Zipcode.create(zip: 22724).distzips.create([{district: seven}])
Zipcode.create(zip: 22726).distzips.create([{district: seven}])
Zipcode.create(zip: 22727).distzips.create([{district: five}])
Zipcode.create(zip: 22728).distzips.create([{district: one}, {district: five}])
Zipcode.create(zip: 22729).distzips.create([{district: seven}])
Zipcode.create(zip: 22730).distzips.create([{district: five}])
Zipcode.create(zip: 22731).distzips.create([{district: five}])
Zipcode.create(zip: 22732).distzips.create([{district: five}])
Zipcode.create(zip: 22733).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22734).distzips.create([{district: one}, {district: five}, {district: seven}])
Zipcode.create(zip: 22735).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22736).distzips.create([{district: seven}])
Zipcode.create(zip: 22737).distzips.create([{district: seven}])
Zipcode.create(zip: 22738).distzips.create([{district: five}])
Zipcode.create(zip: 22740).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22741).distzips.create([{district: seven}])
Zipcode.create(zip: 22742).distzips.create([{district: one}])
Zipcode.create(zip: 22743).distzips.create([{district: five}])
Zipcode.create(zip: 22747).distzips.create([{district: five}])
Zipcode.create(zip: 22749).distzips.create([{district: five}])
Zipcode.create(zip: 22801).distzips.create([{district: six}])
Zipcode.create(zip: 22802).distzips.create([{district: six}])
Zipcode.create(zip: 22807).distzips.create([{district: six}])
Zipcode.create(zip: 22810).distzips.create([{district: six}])
Zipcode.create(zip: 22811).distzips.create([{district: six}])
Zipcode.create(zip: 22812).distzips.create([{district: six}])
Zipcode.create(zip: 22815).distzips.create([{district: six}])
Zipcode.create(zip: 22820).distzips.create([{district: six}])
Zipcode.create(zip: 22821).distzips.create([{district: six}])
Zipcode.create(zip: 22824).distzips.create([{district: six}])
Zipcode.create(zip: 22827).distzips.create([{district: six}])
Zipcode.create(zip: 22830).distzips.create([{district: six}])
Zipcode.create(zip: 22831).distzips.create([{district: six}])
Zipcode.create(zip: 22832).distzips.create([{district: six}])
Zipcode.create(zip: 22834).distzips.create([{district: six}])
Zipcode.create(zip: 22835).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 22840).distzips.create([{district: six}])
Zipcode.create(zip: 22841).distzips.create([{district: six}])
Zipcode.create(zip: 22842).distzips.create([{district: six}])
Zipcode.create(zip: 22843).distzips.create([{district: six}])
Zipcode.create(zip: 22844).distzips.create([{district: six}])
Zipcode.create(zip: 22845).distzips.create([{district: six}])
Zipcode.create(zip: 22846).distzips.create([{district: six}])
Zipcode.create(zip: 22847).distzips.create([{district: six}])
Zipcode.create(zip: 22849).distzips.create([{district: six}])
Zipcode.create(zip: 22850).distzips.create([{district: six}])
Zipcode.create(zip: 22851).distzips.create([{district: six}])
Zipcode.create(zip: 22853).distzips.create([{district: six}])
Zipcode.create(zip: 22901).distzips.create([{district: five}])
Zipcode.create(zip: 22902).distzips.create([{district: five}])
Zipcode.create(zip: 22903).distzips.create([{district: five}])
Zipcode.create(zip: 22904).distzips.create([{district: five}])
Zipcode.create(zip: 22911).distzips.create([{district: five}])
Zipcode.create(zip: 22920).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 22922).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 22923).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22931).distzips.create([{district: five}])
Zipcode.create(zip: 22932).distzips.create([{district: five}])
Zipcode.create(zip: 22935).distzips.create([{district: five}])
Zipcode.create(zip: 22936).distzips.create([{district: five}])
Zipcode.create(zip: 22937).distzips.create([{district: five}])
Zipcode.create(zip: 22938).distzips.create([{district: five}])
Zipcode.create(zip: 22939).distzips.create([{district: six}])
Zipcode.create(zip: 22940).distzips.create([{district: five}])
Zipcode.create(zip: 22942).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22943).distzips.create([{district: five}])
Zipcode.create(zip: 22946).distzips.create([{district: five}])
Zipcode.create(zip: 22947).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22948).distzips.create([{district: five}])
Zipcode.create(zip: 22949).distzips.create([{district: five}])
Zipcode.create(zip: 22952).distzips.create([{district: six}])
Zipcode.create(zip: 22958).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 22959).distzips.create([{district: five}])
Zipcode.create(zip: 22960).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22963).distzips.create([{district: five}])
Zipcode.create(zip: 22964).distzips.create([{district: five}])
Zipcode.create(zip: 22967).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 22968).distzips.create([{district: five}])
Zipcode.create(zip: 22969).distzips.create([{district: five}])
Zipcode.create(zip: 22971).distzips.create([{district: five}])
Zipcode.create(zip: 22972).distzips.create([{district: seven}])
Zipcode.create(zip: 22973).distzips.create([{district: five}])
Zipcode.create(zip: 22974).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 22976).distzips.create([{district: five}])
Zipcode.create(zip: 22980).distzips.create([{district: six}])
Zipcode.create(zip: 22989).distzips.create([{district: five}])
Zipcode.create(zip: 23002).distzips.create([{district: four}])
Zipcode.create(zip: 23004).distzips.create([{district: five}])
Zipcode.create(zip: 23005).distzips.create([{district: seven}])
Zipcode.create(zip: 23009).distzips.create([{district: one}])
Zipcode.create(zip: 23011).distzips.create([{district: seven}])
Zipcode.create(zip: 23015).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 23021).distzips.create([{district: one}])
Zipcode.create(zip: 23022).distzips.create([{district: five}])
Zipcode.create(zip: 23023).distzips.create([{district: one}])
Zipcode.create(zip: 23024).distzips.create([{district: seven}])
Zipcode.create(zip: 23025).distzips.create([{district: one}])
Zipcode.create(zip: 23027).distzips.create([{district: five}])
Zipcode.create(zip: 23030).distzips.create([{district: three}])
Zipcode.create(zip: 23032).distzips.create([{district: one}])
Zipcode.create(zip: 23035).distzips.create([{district: one}])
Zipcode.create(zip: 23038).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 23039).distzips.create([{district: seven}])
Zipcode.create(zip: 23040).distzips.create([{district: five}])
Zipcode.create(zip: 23043).distzips.create([{district: one}])
Zipcode.create(zip: 23045).distzips.create([{district: one}])
Zipcode.create(zip: 23047).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 23050).distzips.create([{district: one}])
Zipcode.create(zip: 23055).distzips.create([{district: five}])
Zipcode.create(zip: 23056).distzips.create([{district: one}])
Zipcode.create(zip: 23059).distzips.create([{district: seven}])
Zipcode.create(zip: 23060).distzips.create([{district: seven}])
Zipcode.create(zip: 23061).distzips.create([{district: one}])
Zipcode.create(zip: 23062).distzips.create([{district: one}])
Zipcode.create(zip: 23063).distzips.create([{district: seven}])
Zipcode.create(zip: 23064).distzips.create([{district: one}])
Zipcode.create(zip: 23065).distzips.create([{district: seven}])
Zipcode.create(zip: 23066).distzips.create([{district: one}])
Zipcode.create(zip: 23068).distzips.create([{district: one}])
Zipcode.create(zip: 23069).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 23070).distzips.create([{district: one}])
Zipcode.create(zip: 23071).distzips.create([{district: one}])
Zipcode.create(zip: 23072).distzips.create([{district: one}])
Zipcode.create(zip: 23075).distzips.create([{district: three}])
Zipcode.create(zip: 23076).distzips.create([{district: one}])
Zipcode.create(zip: 23079).distzips.create([{district: one}])
Zipcode.create(zip: 23083).distzips.create([{district: four}])
Zipcode.create(zip: 23084).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 23085).distzips.create([{district: one}])
Zipcode.create(zip: 23086).distzips.create([{district: one}])
Zipcode.create(zip: 23089).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 23091).distzips.create([{district: one}])
Zipcode.create(zip: 23092).distzips.create([{district: one}])
Zipcode.create(zip: 23093).distzips.create([{district: five}, {district: seven}])
Zipcode.create(zip: 23102).distzips.create([{district: seven}])
Zipcode.create(zip: 23103).distzips.create([{district: seven}])
Zipcode.create(zip: 23106).distzips.create([{district: one}])
Zipcode.create(zip: 23108).distzips.create([{district: one}])
Zipcode.create(zip: 23109).distzips.create([{district: one}])
Zipcode.create(zip: 23110).distzips.create([{district: one}])
Zipcode.create(zip: 23111).distzips.create([{district: seven}])
Zipcode.create(zip: 23112).distzips.create([{district: four}, {district: seven}])
Zipcode.create(zip: 23113).distzips.create([{district: four}, {district: seven}])
Zipcode.create(zip: 23114).distzips.create([{district: seven}])
Zipcode.create(zip: 23115).distzips.create([{district: one}])
Zipcode.create(zip: 23116).distzips.create([{district: seven}])
Zipcode.create(zip: 23117).distzips.create([{district: seven}])
Zipcode.create(zip: 23119).distzips.create([{district: one}])
Zipcode.create(zip: 23120).distzips.create([{district: four}, {district: seven}])
Zipcode.create(zip: 23123).distzips.create([{district: five}])
Zipcode.create(zip: 23124).distzips.create([{district: seven}])
Zipcode.create(zip: 23125).distzips.create([{district: one}])
Zipcode.create(zip: 23126).distzips.create([{district: one}])
Zipcode.create(zip: 23128).distzips.create([{district: one}])
Zipcode.create(zip: 23129).distzips.create([{district: seven}])
Zipcode.create(zip: 23130).distzips.create([{district: one}])
Zipcode.create(zip: 23138).distzips.create([{district: one}])
Zipcode.create(zip: 23139).distzips.create([{district: four}, {district: five}])
Zipcode.create(zip: 23140).distzips.create([{district: three}, {district: seven}])
Zipcode.create(zip: 23141).distzips.create([{district: seven}])
Zipcode.create(zip: 23146).distzips.create([{district: seven}])
Zipcode.create(zip: 23148).distzips.create([{district: one}])
Zipcode.create(zip: 23149).distzips.create([{district: one}])
Zipcode.create(zip: 23150).distzips.create([{district: three}])
Zipcode.create(zip: 23153).distzips.create([{district: seven}])
Zipcode.create(zip: 23156).distzips.create([{district: one}])
Zipcode.create(zip: 23160).distzips.create([{district: four}, {district: seven}])
Zipcode.create(zip: 23161).distzips.create([{district: one}])
Zipcode.create(zip: 23163).distzips.create([{district: one}])
Zipcode.create(zip: 23168).distzips.create([{district: one}])
Zipcode.create(zip: 23169).distzips.create([{district: one}])
Zipcode.create(zip: 23173).distzips.create([{district: seven}])
Zipcode.create(zip: 23175).distzips.create([{district: one}])
Zipcode.create(zip: 23176).distzips.create([{district: one}])
Zipcode.create(zip: 23177).distzips.create([{district: one}])
Zipcode.create(zip: 23180).distzips.create([{district: one}])
Zipcode.create(zip: 23181).distzips.create([{district: one}, {district: seven}])
Zipcode.create(zip: 23185).distzips.create([{district: one}, {district: three}])
Zipcode.create(zip: 23187).distzips.create([{district: one}])
Zipcode.create(zip: 23188).distzips.create([{district: one}])
Zipcode.create(zip: 23192).distzips.create([{district: seven}])
Zipcode.create(zip: 23219).distzips.create([{district: three}])
Zipcode.create(zip: 23220).distzips.create([{district: three}])
Zipcode.create(zip: 23221).distzips.create([{district: three}, {district: seven}])
Zipcode.create(zip: 23222).distzips.create([{district: three}])
Zipcode.create(zip: 23223).distzips.create([{district: three}])
Zipcode.create(zip: 23224).distzips.create([{district: three}, {district: seven}])
Zipcode.create(zip: 23225).distzips.create([{district: three}, {district: seven}])
Zipcode.create(zip: 23226).distzips.create([{district: seven}])
Zipcode.create(zip: 23227).distzips.create([{district: three}, {district: seven}])
Zipcode.create(zip: 23228).distzips.create([{district: seven}])
Zipcode.create(zip: 23229).distzips.create([{district: seven}])
Zipcode.create(zip: 23230).distzips.create([{district: three}, {district: seven}])
Zipcode.create(zip: 23231).distzips.create([{district: three}])
Zipcode.create(zip: 23233).distzips.create([{district: seven}])
Zipcode.create(zip: 23234).distzips.create([{district: three}, {district: four}, {district: seven}])
Zipcode.create(zip: 23235).distzips.create([{district: seven}])
Zipcode.create(zip: 23236).distzips.create([{district: four}, {district: seven}])
Zipcode.create(zip: 23237).distzips.create([{district: four}])
Zipcode.create(zip: 23238).distzips.create([{district: seven}])
Zipcode.create(zip: 23250).distzips.create([{district: three}])
Zipcode.create(zip: 23294).distzips.create([{district: seven}])
Zipcode.create(zip: 23301).distzips.create([{district: two}])
Zipcode.create(zip: 23302).distzips.create([{district: two}])
Zipcode.create(zip: 23303).distzips.create([{district: two}])
Zipcode.create(zip: 23304).distzips.create([{district: four}])
Zipcode.create(zip: 23306).distzips.create([{district: two}])
Zipcode.create(zip: 23307).distzips.create([{district: two}])
Zipcode.create(zip: 23308).distzips.create([{district: two}])
Zipcode.create(zip: 23310).distzips.create([{district: two}])
Zipcode.create(zip: 23313).distzips.create([{district: two}])
Zipcode.create(zip: 23314).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23315).distzips.create([{district: four}])
Zipcode.create(zip: 23316).distzips.create([{district: two}])
Zipcode.create(zip: 23320).distzips.create([{district: four}])
Zipcode.create(zip: 23321).distzips.create([{district: four}])
Zipcode.create(zip: 23322).distzips.create([{district: four}])
Zipcode.create(zip: 23323).distzips.create([{district: four}])
Zipcode.create(zip: 23324).distzips.create([{district: four}])
Zipcode.create(zip: 23325).distzips.create([{district: four}])
Zipcode.create(zip: 23336).distzips.create([{district: two}])
Zipcode.create(zip: 23337).distzips.create([{district: two}])
Zipcode.create(zip: 23347).distzips.create([{district: two}])
Zipcode.create(zip: 23350).distzips.create([{district: two}])
Zipcode.create(zip: 23354).distzips.create([{district: two}])
Zipcode.create(zip: 23356).distzips.create([{district: two}])
Zipcode.create(zip: 23357).distzips.create([{district: two}])
Zipcode.create(zip: 23358).distzips.create([{district: two}])
Zipcode.create(zip: 23359).distzips.create([{district: two}])
Zipcode.create(zip: 23389).distzips.create([{district: two}])
Zipcode.create(zip: 23395).distzips.create([{district: two}])
Zipcode.create(zip: 23398).distzips.create([{district: two}])
Zipcode.create(zip: 23401).distzips.create([{district: two}])
Zipcode.create(zip: 23405).distzips.create([{district: two}])
Zipcode.create(zip: 23407).distzips.create([{district: two}])
Zipcode.create(zip: 23408).distzips.create([{district: two}])
Zipcode.create(zip: 23409).distzips.create([{district: two}])
Zipcode.create(zip: 23410).distzips.create([{district: two}])
Zipcode.create(zip: 23413).distzips.create([{district: two}])
Zipcode.create(zip: 23414).distzips.create([{district: two}])
Zipcode.create(zip: 23415).distzips.create([{district: two}])
Zipcode.create(zip: 23416).distzips.create([{district: two}])
Zipcode.create(zip: 23417).distzips.create([{district: two}])
Zipcode.create(zip: 23418).distzips.create([{district: two}])
Zipcode.create(zip: 23420).distzips.create([{district: two}])
Zipcode.create(zip: 23421).distzips.create([{district: two}])
Zipcode.create(zip: 23422).distzips.create([{district: two}])
Zipcode.create(zip: 23423).distzips.create([{district: two}])
Zipcode.create(zip: 23426).distzips.create([{district: two}])
Zipcode.create(zip: 23427).distzips.create([{district: two}])
Zipcode.create(zip: 23430).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23432).distzips.create([{district: four}])
Zipcode.create(zip: 23433).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23434).distzips.create([{district: four}])
Zipcode.create(zip: 23435).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23436).distzips.create([{district: four}])
Zipcode.create(zip: 23437).distzips.create([{district: four}])
Zipcode.create(zip: 23438).distzips.create([{district: four}])
Zipcode.create(zip: 23440).distzips.create([{district: two}])
Zipcode.create(zip: 23441).distzips.create([{district: two}])
Zipcode.create(zip: 23442).distzips.create([{district: two}])
Zipcode.create(zip: 23451).distzips.create([{district: two}])
Zipcode.create(zip: 23452).distzips.create([{district: two}])
Zipcode.create(zip: 23453).distzips.create([{district: two}])
Zipcode.create(zip: 23454).distzips.create([{district: two}])
Zipcode.create(zip: 23455).distzips.create([{district: two}])
Zipcode.create(zip: 23456).distzips.create([{district: two}])
Zipcode.create(zip: 23457).distzips.create([{district: two}])
Zipcode.create(zip: 23459).distzips.create([{district: two}])
Zipcode.create(zip: 23460).distzips.create([{district: two}])
Zipcode.create(zip: 23461).distzips.create([{district: two}])
Zipcode.create(zip: 23462).distzips.create([{district: two}])
Zipcode.create(zip: 23464).distzips.create([{district: two}])
Zipcode.create(zip: 23480).distzips.create([{district: two}])
Zipcode.create(zip: 23486).distzips.create([{district: two}])
Zipcode.create(zip: 23487).distzips.create([{district: four}])
Zipcode.create(zip: 23488).distzips.create([{district: two}])
Zipcode.create(zip: 23502).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23503).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23504).distzips.create([{district: three}])
Zipcode.create(zip: 23505).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23507).distzips.create([{district: three}])
Zipcode.create(zip: 23508).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23509).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23510).distzips.create([{district: three}])
Zipcode.create(zip: 23511).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23513).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23517).distzips.create([{district: three}])
Zipcode.create(zip: 23518).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23523).distzips.create([{district: three}])
Zipcode.create(zip: 23551).distzips.create([{district: three}])
Zipcode.create(zip: 23601).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23602).distzips.create([{district: one}, {district: two}, {district: three}])
Zipcode.create(zip: 23603).distzips.create([{district: one}, {district: three}])
Zipcode.create(zip: 23604).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23605).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23606).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23607).distzips.create([{district: three}])
Zipcode.create(zip: 23608).distzips.create([{district: one}, {district: two}, {district: three}])
Zipcode.create(zip: 23651).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23661).distzips.create([{district: three}])
Zipcode.create(zip: 23662).distzips.create([{district: one}])
Zipcode.create(zip: 23663).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23664).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23665).distzips.create([{district: one}, {district: two}])
Zipcode.create(zip: 23666).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23669).distzips.create([{district: two}, {district: three}])
Zipcode.create(zip: 23690).distzips.create([{district: one}])
Zipcode.create(zip: 23691).distzips.create([{district: one}])
Zipcode.create(zip: 23692).distzips.create([{district: one}])
Zipcode.create(zip: 23693).distzips.create([{district: one}])
Zipcode.create(zip: 23696).distzips.create([{district: one}])
Zipcode.create(zip: 23701).distzips.create([{district: three}])
Zipcode.create(zip: 23702).distzips.create([{district: three}])
Zipcode.create(zip: 23703).distzips.create([{district: three}])
Zipcode.create(zip: 23704).distzips.create([{district: three}])
Zipcode.create(zip: 23707).distzips.create([{district: three}])
Zipcode.create(zip: 23708).distzips.create([{district: three}])
Zipcode.create(zip: 23709).distzips.create([{district: three}])
Zipcode.create(zip: 23801).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23803).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23805).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23806).distzips.create([{district: four}])
Zipcode.create(zip: 23821).distzips.create([{district: five}])
Zipcode.create(zip: 23824).distzips.create([{district: four}, {district: five}])
Zipcode.create(zip: 23827).distzips.create([{district: four}])
Zipcode.create(zip: 23828).distzips.create([{district: four}])
Zipcode.create(zip: 23829).distzips.create([{district: four}])
Zipcode.create(zip: 23830).distzips.create([{district: four}])
Zipcode.create(zip: 23831).distzips.create([{district: four}])
Zipcode.create(zip: 23832).distzips.create([{district: four}, {district: seven}])
Zipcode.create(zip: 23833).distzips.create([{district: four}])
Zipcode.create(zip: 23834).distzips.create([{district: four}])
Zipcode.create(zip: 23836).distzips.create([{district: four}])
Zipcode.create(zip: 23837).distzips.create([{district: four}])
Zipcode.create(zip: 23838).distzips.create([{district: four}])
Zipcode.create(zip: 23839).distzips.create([{district: three}])
Zipcode.create(zip: 23840).distzips.create([{district: four}])
Zipcode.create(zip: 23841).distzips.create([{district: four}])
Zipcode.create(zip: 23842).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23843).distzips.create([{district: five}])
Zipcode.create(zip: 23844).distzips.create([{district: four}])
Zipcode.create(zip: 23845).distzips.create([{district: five}])
Zipcode.create(zip: 23846).distzips.create([{district: three}])
Zipcode.create(zip: 23847).distzips.create([{district: four}, {district: five}])
Zipcode.create(zip: 23850).distzips.create([{district: four}])
Zipcode.create(zip: 23851).distzips.create([{district: four}])
Zipcode.create(zip: 23856).distzips.create([{district: four}, {district: five}])
Zipcode.create(zip: 23857).distzips.create([{district: five}])
Zipcode.create(zip: 23860).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23866).distzips.create([{district: four}])
Zipcode.create(zip: 23867).distzips.create([{district: four}])
Zipcode.create(zip: 23868).distzips.create([{district: five}])
Zipcode.create(zip: 23872).distzips.create([{district: four}])
Zipcode.create(zip: 23874).distzips.create([{district: four}])
Zipcode.create(zip: 23875).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23876).distzips.create([{district: five}])
Zipcode.create(zip: 23878).distzips.create([{district: four}])
Zipcode.create(zip: 23879).distzips.create([{district: four}])
Zipcode.create(zip: 23881).distzips.create([{district: three}])
Zipcode.create(zip: 23882).distzips.create([{district: four}])
Zipcode.create(zip: 23883).distzips.create([{district: three}])
Zipcode.create(zip: 23884).distzips.create([{district: four}])
Zipcode.create(zip: 23885).distzips.create([{district: four}])
Zipcode.create(zip: 23887).distzips.create([{district: five}])
Zipcode.create(zip: 23888).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23889).distzips.create([{district: five}])
Zipcode.create(zip: 23890).distzips.create([{district: three}, {district: four}])
Zipcode.create(zip: 23891).distzips.create([{district: four}])
Zipcode.create(zip: 23893).distzips.create([{district: five}])
Zipcode.create(zip: 23894).distzips.create([{district: four}])
Zipcode.create(zip: 23897).distzips.create([{district: four}])
Zipcode.create(zip: 23898).distzips.create([{district: four}])
Zipcode.create(zip: 23899).distzips.create([{district: three}])
Zipcode.create(zip: 23901).distzips.create([{district: five}])
Zipcode.create(zip: 23909).distzips.create([{district: five}])
Zipcode.create(zip: 23915).distzips.create([{district: five}])
Zipcode.create(zip: 23917).distzips.create([{district: five}])
Zipcode.create(zip: 23919).distzips.create([{district: five}])
Zipcode.create(zip: 23920).distzips.create([{district: five}])
Zipcode.create(zip: 23921).distzips.create([{district: five}])
Zipcode.create(zip: 23922).distzips.create([{district: four}, {district: five}])
Zipcode.create(zip: 23923).distzips.create([{district: five}])
Zipcode.create(zip: 23924).distzips.create([{district: five}])
Zipcode.create(zip: 23927).distzips.create([{district: five}])
Zipcode.create(zip: 23930).distzips.create([{district: four}])
Zipcode.create(zip: 23934).distzips.create([{district: five}])
Zipcode.create(zip: 23936).distzips.create([{district: five}])
Zipcode.create(zip: 23937).distzips.create([{district: five}])
Zipcode.create(zip: 23938).distzips.create([{district: five}])
Zipcode.create(zip: 23942).distzips.create([{district: five}])
Zipcode.create(zip: 23943).distzips.create([{district: five}])
Zipcode.create(zip: 23944).distzips.create([{district: five}])
Zipcode.create(zip: 23947).distzips.create([{district: five}])
Zipcode.create(zip: 23950).distzips.create([{district: five}])
Zipcode.create(zip: 23952).distzips.create([{district: five}])
Zipcode.create(zip: 23954).distzips.create([{district: five}])
Zipcode.create(zip: 23958).distzips.create([{district: five}])
Zipcode.create(zip: 23959).distzips.create([{district: five}])
Zipcode.create(zip: 23960).distzips.create([{district: five}])
Zipcode.create(zip: 23962).distzips.create([{district: five}])
Zipcode.create(zip: 23963).distzips.create([{district: five}])
Zipcode.create(zip: 23964).distzips.create([{district: five}])
Zipcode.create(zip: 23966).distzips.create([{district: four}, {district: five}])
Zipcode.create(zip: 23967).distzips.create([{district: five}])
Zipcode.create(zip: 23968).distzips.create([{district: five}])
Zipcode.create(zip: 23970).distzips.create([{district: five}])
Zipcode.create(zip: 23974).distzips.create([{district: five}])
Zipcode.create(zip: 23976).distzips.create([{district: five}])
Zipcode.create(zip: 24011).distzips.create([{district: six}])
Zipcode.create(zip: 24012).distzips.create([{district: six}])
Zipcode.create(zip: 24013).distzips.create([{district: six}])
Zipcode.create(zip: 24014).distzips.create([{district: six}])
Zipcode.create(zip: 24015).distzips.create([{district: six}])
Zipcode.create(zip: 24016).distzips.create([{district: six}])
Zipcode.create(zip: 24017).distzips.create([{district: six}])
Zipcode.create(zip: 24018).distzips.create([{district: six}, {district: nine}])
Zipcode.create(zip: 24019).distzips.create([{district: six}, {district: nine}])
Zipcode.create(zip: 24020).distzips.create([{district: six}])
Zipcode.create(zip: 24053).distzips.create([{district: nine}])
Zipcode.create(zip: 24054).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24055).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24058).distzips.create([{district: nine}])
Zipcode.create(zip: 24059).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24060).distzips.create([{district: nine}])
Zipcode.create(zip: 24064).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24065).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24066).distzips.create([{district: six}])
Zipcode.create(zip: 24067).distzips.create([{district: five}])
Zipcode.create(zip: 24069).distzips.create([{district: five}])
Zipcode.create(zip: 24070).distzips.create([{district: nine}])
Zipcode.create(zip: 24072).distzips.create([{district: nine}])
Zipcode.create(zip: 24073).distzips.create([{district: nine}])
Zipcode.create(zip: 24076).distzips.create([{district: nine}])
Zipcode.create(zip: 24077).distzips.create([{district: six}])
Zipcode.create(zip: 24078).distzips.create([{district: nine}])
Zipcode.create(zip: 24079).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24082).distzips.create([{district: nine}])
Zipcode.create(zip: 24083).distzips.create([{district: six}])
Zipcode.create(zip: 24084).distzips.create([{district: nine}])
Zipcode.create(zip: 24085).distzips.create([{district: six}, {district: nine}])
Zipcode.create(zip: 24086).distzips.create([{district: nine}])
Zipcode.create(zip: 24087).distzips.create([{district: nine}])
Zipcode.create(zip: 24088).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24089).distzips.create([{district: nine}])
Zipcode.create(zip: 24090).distzips.create([{district: six}])
Zipcode.create(zip: 24091).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24092).distzips.create([{district: five}])
Zipcode.create(zip: 24093).distzips.create([{district: nine}])
Zipcode.create(zip: 24095).distzips.create([{district: five}])
Zipcode.create(zip: 24101).distzips.create([{district: five}])
Zipcode.create(zip: 24102).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24104).distzips.create([{district: five}])
Zipcode.create(zip: 24105).distzips.create([{district: nine}])
Zipcode.create(zip: 24112).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24120).distzips.create([{district: nine}])
Zipcode.create(zip: 24121).distzips.create([{district: five}])
Zipcode.create(zip: 24122).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24124).distzips.create([{district: nine}])
Zipcode.create(zip: 24127).distzips.create([{district: nine}])
Zipcode.create(zip: 24128).distzips.create([{district: nine}])
Zipcode.create(zip: 24130).distzips.create([{district: six}])
Zipcode.create(zip: 24131).distzips.create([{district: nine}])
Zipcode.create(zip: 24132).distzips.create([{district: nine}])
Zipcode.create(zip: 24133).distzips.create([{district: nine}])
Zipcode.create(zip: 24134).distzips.create([{district: nine}])
Zipcode.create(zip: 24136).distzips.create([{district: nine}])
Zipcode.create(zip: 24137).distzips.create([{district: five}])
Zipcode.create(zip: 24138).distzips.create([{district: nine}])
Zipcode.create(zip: 24139).distzips.create([{district: five}])
Zipcode.create(zip: 24141).distzips.create([{district: nine}])
Zipcode.create(zip: 24142).distzips.create([{district: nine}])
Zipcode.create(zip: 24147).distzips.create([{district: nine}])
Zipcode.create(zip: 24148).distzips.create([{district: five}, {district: nine}])
Zipcode.create(zip: 24149).distzips.create([{district: nine}])
Zipcode.create(zip: 24150).distzips.create([{district: nine}])
Zipcode.create(zip: 24151).distzips.create([{district: five}])
Zipcode.create(zip: 24153).distzips.create([{district: six}, {district: nine}])
Zipcode.create(zip: 24161).distzips.create([{district: five}])
Zipcode.create(zip: 24162).distzips.create([{district: nine}])
Zipcode.create(zip: 24165).distzips.create([{district: nine}])
Zipcode.create(zip: 24167).distzips.create([{district: nine}])
Zipcode.create(zip: 24168).distzips.create([{district: nine}])
Zipcode.create(zip: 24171).distzips.create([{district: nine}])
Zipcode.create(zip: 24174).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24175).distzips.create([{district: six}, {district: nine}])
Zipcode.create(zip: 24176).distzips.create([{district: five}])
Zipcode.create(zip: 24179).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24184).distzips.create([{district: five}])
Zipcode.create(zip: 24185).distzips.create([{district: nine}])
Zipcode.create(zip: 24201).distzips.create([{district: nine}])
Zipcode.create(zip: 24202).distzips.create([{district: nine}])
Zipcode.create(zip: 24210).distzips.create([{district: nine}])
Zipcode.create(zip: 24211).distzips.create([{district: nine}])
Zipcode.create(zip: 24216).distzips.create([{district: nine}])
Zipcode.create(zip: 24217).distzips.create([{district: nine}])
Zipcode.create(zip: 24219).distzips.create([{district: nine}])
Zipcode.create(zip: 24220).distzips.create([{district: nine}])
Zipcode.create(zip: 24221).distzips.create([{district: nine}])
Zipcode.create(zip: 24224).distzips.create([{district: nine}])
Zipcode.create(zip: 24225).distzips.create([{district: nine}])
Zipcode.create(zip: 24226).distzips.create([{district: nine}])
Zipcode.create(zip: 24228).distzips.create([{district: nine}])
Zipcode.create(zip: 24230).distzips.create([{district: nine}])
Zipcode.create(zip: 24236).distzips.create([{district: nine}])
Zipcode.create(zip: 24237).distzips.create([{district: nine}])
Zipcode.create(zip: 24239).distzips.create([{district: nine}])
Zipcode.create(zip: 24243).distzips.create([{district: nine}])
Zipcode.create(zip: 24244).distzips.create([{district: nine}])
Zipcode.create(zip: 24245).distzips.create([{district: nine}])
Zipcode.create(zip: 24246).distzips.create([{district: nine}])
Zipcode.create(zip: 24248).distzips.create([{district: nine}])
Zipcode.create(zip: 24250).distzips.create([{district: nine}])
Zipcode.create(zip: 24251).distzips.create([{district: nine}])
Zipcode.create(zip: 24256).distzips.create([{district: nine}])
Zipcode.create(zip: 24258).distzips.create([{district: nine}])
Zipcode.create(zip: 24260).distzips.create([{district: nine}])
Zipcode.create(zip: 24263).distzips.create([{district: nine}])
Zipcode.create(zip: 24265).distzips.create([{district: nine}])
Zipcode.create(zip: 24266).distzips.create([{district: nine}])
Zipcode.create(zip: 24269).distzips.create([{district: nine}])
Zipcode.create(zip: 24270).distzips.create([{district: nine}])
Zipcode.create(zip: 24271).distzips.create([{district: nine}])
Zipcode.create(zip: 24272).distzips.create([{district: nine}])
Zipcode.create(zip: 24273).distzips.create([{district: nine}])
Zipcode.create(zip: 24277).distzips.create([{district: nine}])
Zipcode.create(zip: 24279).distzips.create([{district: nine}])
Zipcode.create(zip: 24280).distzips.create([{district: nine}])
Zipcode.create(zip: 24281).distzips.create([{district: nine}])
Zipcode.create(zip: 24282).distzips.create([{district: nine}])
Zipcode.create(zip: 24283).distzips.create([{district: nine}])
Zipcode.create(zip: 24290).distzips.create([{district: nine}])
Zipcode.create(zip: 24292).distzips.create([{district: nine}])
Zipcode.create(zip: 24293).distzips.create([{district: nine}])
Zipcode.create(zip: 24301).distzips.create([{district: nine}])
Zipcode.create(zip: 24311).distzips.create([{district: nine}])
Zipcode.create(zip: 24312).distzips.create([{district: nine}])
Zipcode.create(zip: 24313).distzips.create([{district: nine}])
Zipcode.create(zip: 24314).distzips.create([{district: nine}])
Zipcode.create(zip: 24315).distzips.create([{district: nine}])
Zipcode.create(zip: 24316).distzips.create([{district: nine}])
Zipcode.create(zip: 24317).distzips.create([{district: nine}])
Zipcode.create(zip: 24318).distzips.create([{district: nine}])
Zipcode.create(zip: 24319).distzips.create([{district: nine}])
Zipcode.create(zip: 24322).distzips.create([{district: nine}])
Zipcode.create(zip: 24323).distzips.create([{district: nine}])
Zipcode.create(zip: 24324).distzips.create([{district: nine}])
Zipcode.create(zip: 24325).distzips.create([{district: nine}])
Zipcode.create(zip: 24326).distzips.create([{district: nine}])
Zipcode.create(zip: 24328).distzips.create([{district: nine}])
Zipcode.create(zip: 24330).distzips.create([{district: nine}])
Zipcode.create(zip: 24333).distzips.create([{district: nine}])
Zipcode.create(zip: 24340).distzips.create([{district: nine}])
Zipcode.create(zip: 24343).distzips.create([{district: nine}])
Zipcode.create(zip: 24347).distzips.create([{district: nine}])
Zipcode.create(zip: 24348).distzips.create([{district: nine}])
Zipcode.create(zip: 24350).distzips.create([{district: nine}])
Zipcode.create(zip: 24351).distzips.create([{district: nine}])
Zipcode.create(zip: 24352).distzips.create([{district: nine}])
Zipcode.create(zip: 24354).distzips.create([{district: nine}])
Zipcode.create(zip: 24360).distzips.create([{district: nine}])
Zipcode.create(zip: 24361).distzips.create([{district: nine}])
Zipcode.create(zip: 24363).distzips.create([{district: nine}])
Zipcode.create(zip: 24366).distzips.create([{district: nine}])
Zipcode.create(zip: 24368).distzips.create([{district: nine}])
Zipcode.create(zip: 24370).distzips.create([{district: nine}])
Zipcode.create(zip: 24374).distzips.create([{district: nine}])
Zipcode.create(zip: 24375).distzips.create([{district: nine}])
Zipcode.create(zip: 24377).distzips.create([{district: nine}])
Zipcode.create(zip: 24378).distzips.create([{district: nine}])
Zipcode.create(zip: 24380).distzips.create([{district: nine}])
Zipcode.create(zip: 24381).distzips.create([{district: nine}])
Zipcode.create(zip: 24382).distzips.create([{district: nine}])
Zipcode.create(zip: 24401).distzips.create([{district: six}])
Zipcode.create(zip: 24411).distzips.create([{district: six}])
Zipcode.create(zip: 24412).distzips.create([{district: six}])
Zipcode.create(zip: 24413).distzips.create([{district: six}])
Zipcode.create(zip: 24415).distzips.create([{district: six}])
Zipcode.create(zip: 24416).distzips.create([{district: six}])
Zipcode.create(zip: 24421).distzips.create([{district: six}])
Zipcode.create(zip: 24422).distzips.create([{district: six}, {district: nine}])
Zipcode.create(zip: 24426).distzips.create([{district: nine}])
Zipcode.create(zip: 24430).distzips.create([{district: six}])
Zipcode.create(zip: 24431).distzips.create([{district: six}])
Zipcode.create(zip: 24432).distzips.create([{district: six}])
Zipcode.create(zip: 24433).distzips.create([{district: six}])
Zipcode.create(zip: 24435).distzips.create([{district: six}])
Zipcode.create(zip: 24437).distzips.create([{district: six}])
Zipcode.create(zip: 24439).distzips.create([{district: six}])
Zipcode.create(zip: 24440).distzips.create([{district: six}])
Zipcode.create(zip: 24441).distzips.create([{district: six}])
Zipcode.create(zip: 24442).distzips.create([{district: six}])
Zipcode.create(zip: 24445).distzips.create([{district: six}, {district: nine}])
Zipcode.create(zip: 24448).distzips.create([{district: nine}])
Zipcode.create(zip: 24450).distzips.create([{district: six}])
Zipcode.create(zip: 24457).distzips.create([{district: nine}])
Zipcode.create(zip: 24458).distzips.create([{district: six}])
Zipcode.create(zip: 24459).distzips.create([{district: six}])
Zipcode.create(zip: 24460).distzips.create([{district: six}])
Zipcode.create(zip: 24464).distzips.create([{district: five}])
Zipcode.create(zip: 24465).distzips.create([{district: six}])
Zipcode.create(zip: 24467).distzips.create([{district: six}])
Zipcode.create(zip: 24471).distzips.create([{district: six}])
Zipcode.create(zip: 24472).distzips.create([{district: six}])
Zipcode.create(zip: 24473).distzips.create([{district: six}])
Zipcode.create(zip: 24474).distzips.create([{district: nine}])
Zipcode.create(zip: 24476).distzips.create([{district: six}])
Zipcode.create(zip: 24477).distzips.create([{district: six}])
Zipcode.create(zip: 24479).distzips.create([{district: six}])
Zipcode.create(zip: 24482).distzips.create([{district: six}])
Zipcode.create(zip: 24483).distzips.create([{district: six}])
Zipcode.create(zip: 24484).distzips.create([{district: six}])
Zipcode.create(zip: 24485).distzips.create([{district: six}])
Zipcode.create(zip: 24486).distzips.create([{district: six}])
Zipcode.create(zip: 24487).distzips.create([{district: six}])
Zipcode.create(zip: 24501).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24502).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24503).distzips.create([{district: six}])
Zipcode.create(zip: 24504).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24517).distzips.create([{district: five}])
Zipcode.create(zip: 24520).distzips.create([{district: five}])
Zipcode.create(zip: 24521).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24522).distzips.create([{district: five}])
Zipcode.create(zip: 24523).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24526).distzips.create([{district: six}])
Zipcode.create(zip: 24527).distzips.create([{district: five}])
Zipcode.create(zip: 24528).distzips.create([{district: five}])
Zipcode.create(zip: 24529).distzips.create([{district: five}])
Zipcode.create(zip: 24530).distzips.create([{district: five}])
Zipcode.create(zip: 24531).distzips.create([{district: five}])
Zipcode.create(zip: 24534).distzips.create([{district: five}])
Zipcode.create(zip: 24536).distzips.create([{district: six}])
Zipcode.create(zip: 24538).distzips.create([{district: five}])
Zipcode.create(zip: 24539).distzips.create([{district: five}])
Zipcode.create(zip: 24540).distzips.create([{district: five}])
Zipcode.create(zip: 24541).distzips.create([{district: five}])
Zipcode.create(zip: 24549).distzips.create([{district: five}])
Zipcode.create(zip: 24550).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24551).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24553).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24554).distzips.create([{district: five}])
Zipcode.create(zip: 24555).distzips.create([{district: six}])
Zipcode.create(zip: 24556).distzips.create([{district: five}, {district: six}])
Zipcode.create(zip: 24557).distzips.create([{district: five}])
Zipcode.create(zip: 24558).distzips.create([{district: five}])
Zipcode.create(zip: 24562).distzips.create([{district: five}])
Zipcode.create(zip: 24563).distzips.create([{district: five}])
Zipcode.create(zip: 24565).distzips.create([{district: five}])
Zipcode.create(zip: 24566).distzips.create([{district: five}])
Zipcode.create(zip: 24569).distzips.create([{district: five}])
Zipcode.create(zip: 24570).distzips.create([{district: five}])
Zipcode.create(zip: 24571).distzips.create([{district: five}])
Zipcode.create(zip: 24572).distzips.create([{district: six}])
Zipcode.create(zip: 24574).distzips.create([{district: six}])
Zipcode.create(zip: 24577).distzips.create([{district: five}])
Zipcode.create(zip: 24578).distzips.create([{district: six}])
Zipcode.create(zip: 24579).distzips.create([{district: six}])
Zipcode.create(zip: 24580).distzips.create([{district: five}])
Zipcode.create(zip: 24581).distzips.create([{district: five}])
Zipcode.create(zip: 24586).distzips.create([{district: five}])
Zipcode.create(zip: 24588).distzips.create([{district: five}])
Zipcode.create(zip: 24589).distzips.create([{district: five}])
Zipcode.create(zip: 24590).distzips.create([{district: five}])
Zipcode.create(zip: 24592).distzips.create([{district: five}])
Zipcode.create(zip: 24593).distzips.create([{district: five}])
Zipcode.create(zip: 24594).distzips.create([{district: five}])
Zipcode.create(zip: 24595).distzips.create([{district: six}])
Zipcode.create(zip: 24597).distzips.create([{district: five}])
Zipcode.create(zip: 24598).distzips.create([{district: five}])
Zipcode.create(zip: 24599).distzips.create([{district: five}])
Zipcode.create(zip: 24601).distzips.create([{district: nine}])
Zipcode.create(zip: 24602).distzips.create([{district: nine}])
Zipcode.create(zip: 24603).distzips.create([{district: nine}])
Zipcode.create(zip: 24604).distzips.create([{district: nine}])
Zipcode.create(zip: 24605).distzips.create([{district: nine}])
Zipcode.create(zip: 24606).distzips.create([{district: nine}])
Zipcode.create(zip: 24607).distzips.create([{district: nine}])
Zipcode.create(zip: 24609).distzips.create([{district: nine}])
Zipcode.create(zip: 24612).distzips.create([{district: nine}])
Zipcode.create(zip: 24613).distzips.create([{district: nine}])
Zipcode.create(zip: 24614).distzips.create([{district: nine}])
Zipcode.create(zip: 24620).distzips.create([{district: nine}])
Zipcode.create(zip: 24622).distzips.create([{district: nine}])
Zipcode.create(zip: 24628).distzips.create([{district: nine}])
Zipcode.create(zip: 24630).distzips.create([{district: nine}])
Zipcode.create(zip: 24631).distzips.create([{district: nine}])
Zipcode.create(zip: 24634).distzips.create([{district: nine}])
Zipcode.create(zip: 24635).distzips.create([{district: nine}])
Zipcode.create(zip: 24637).distzips.create([{district: nine}])
Zipcode.create(zip: 24639).distzips.create([{district: nine}])
Zipcode.create(zip: 24641).distzips.create([{district: nine}])
Zipcode.create(zip: 24646).distzips.create([{district: nine}])
Zipcode.create(zip: 24649).distzips.create([{district: nine}])
Zipcode.create(zip: 24651).distzips.create([{district: nine}])
Zipcode.create(zip: 24656).distzips.create([{district: nine}])
Zipcode.create(zip: 24657).distzips.create([{district: nine}])
